### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [kaazing/gateway.docker#17]
I want to build this image on arm64 architecture but I don't find to support arm64 at https://oss.sonatype.org/content/repositories/releases/org/kaazing/gateway.distribution/5.6.0/ . So I want to know this image whether or not support arm64 architecture.

**Comment by tianon** [comment]
Since `kaazing-gateway` is `FROM openjdk:...`, this `Dockerfile` _should_ just work as-is with any the architectures supported by `openjdk` (https://github.com/docker-library/official-images/blob/83445dba81738f34d37e13fa811b34841d1d6def/library/openjdk#L63, `amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x`).

See https://github.com/docker-library/official-images#architectures-other-than-amd64 and https://github.com/docker-library/official-images#multiple-architectures for more information about multi-architecture official images. :+1:
